load input_PDBs/alternate_Bchain_C_term_conformation/glargin_pmL1_alt_conf_5layers-delH.pdb    , proteorella
distance (chain B and resid    1 and name O  ), (chain F and resid    2 and name N  )
distance (chain B and resid    2 and name O  ), (chain R and resid    3 and name N  )
distance (chain B and resid    3 and name OD1), (chain R and resid    3 and name ND2)
distance (chain B and resid    3 and name O  ), (chain F and resid    4 and name N  )
distance (chain B and resid    4 and name O  ), (chain B and resid    6 and name N  )
distance (chain B and resid    5 and name O  ), (chain R and resid    6 and name N  )
distance (chain B and resid    6 and name O  ), (chain F and resid    7 and name N  )
distance (chain B and resid    7 and name O  ), (chain F and resid    8 and name N  )
distance (chain B and resid    8 and name O  ), (chain R and resid    9 and name N  )
distance (chain B and resid    9 and name O  ), (chain F and resid    9 and name OG )
distance (chain B and resid    9 and name O  ), (chain F and resid   10 and name N  )
distance (chain B and resid   10 and name O  ), (chain R and resid   11 and name N  )
distance (chain B and resid   11 and name O  ), (chain R and resid   12 and name N  )
distance (chain B and resid   12 and name O  ), (chain F and resid   13 and name N  )
distance (chain B and resid   13 and name O  ), (chain R and resid   14 and name N  )
distance (chain B and resid   13 and name OE1), (chain F and resid   10 and name ND1)
distance (chain B and resid   14 and name O  ), (chain F and resid   15 and name N  )
distance (chain B and resid   15 and name O  ), (chain R and resid   16 and name N  )
distance (chain B and resid   16 and name OH ), (chain E and resid    1 and name N  )
distance (chain B and resid   16 and name O  ), (chain B and resid   18 and name N  )
distance (chain B and resid   17 and name O  ), (chain R and resid   18 and name N  )
distance (chain B and resid   18 and name O  ), (chain F and resid   19 and name N  )
distance (chain B and resid   19 and name O  ), (chain R and resid   20 and name N  )
distance (chain B and resid   20 and name O  ), (chain B and resid   22 and name N  )
distance (chain B and resid   20 and name O  ), (chain B and resid   23 and name N  )
distance (chain B and resid   21 and name OE2), (chain B and resid   22 and name NH1)
distance (chain B and resid   21 and name OE2), (chain H and resid    1 and name N  )
distance (chain B and resid   21 and name O  ), (chain F and resid   22 and name N  )
distance (chain B and resid   21 and name OE1), (chain D and resid    1 and name N  )
distance (chain B and resid   21 and name OE1), (chain H and resid    1 and name N  )
distance (chain B and resid   22 and name O  ), (chain F and resid   23 and name N  )
distance (chain B and resid   23 and name O  ), (chain B and resid   25 and name N  )
distance (chain B and resid   23 and name O  ), (chain F and resid   24 and name N  )
distance (chain B and resid   25 and name O  ), (chain R and resid   26 and name N  )
distance (chain B and resid   27 and name O  ), (chain B and resid   29 and name NZ )
distance (chain D and resid    1 and name O  ), (chain H and resid    2 and name N  )
distance (chain D and resid    2 and name O  ), (chain T and resid    3 and name N  )
distance (chain D and resid    3 and name OD1), (chain T and resid    3 and name ND2)
distance (chain D and resid    3 and name O  ), (chain H and resid    4 and name N  )
distance (chain D and resid    5 and name O  ), (chain T and resid    6 and name N  )
distance (chain D and resid    6 and name O  ), (chain H and resid    7 and name N  )
distance (chain D and resid    7 and name O  ), (chain H and resid    8 and name N  )
distance (chain D and resid    8 and name O  ), (chain T and resid    9 and name N  )
distance (chain D and resid    9 and name OG ), (chain D and resid   10 and name N  )
distance (chain D and resid    9 and name O  ), (chain H and resid    9 and name OG )
distance (chain D and resid    9 and name O  ), (chain H and resid   10 and name N  )
distance (chain D and resid   10 and name O  ), (chain T and resid   11 and name N  )
distance (chain D and resid   11 and name O  ), (chain T and resid   12 and name N  )
distance (chain D and resid   12 and name O  ), (chain H and resid   13 and name N  )
distance (chain D and resid   13 and name O  ), (chain T and resid   14 and name N  )
distance (chain D and resid   13 and name OE1), (chain H and resid   10 and name ND1)
distance (chain D and resid   14 and name O  ), (chain H and resid   15 and name N  )
distance (chain D and resid   15 and name O  ), (chain T and resid   16 and name N  )
distance (chain D and resid   16 and name O  ), (chain D and resid   18 and name N  )
distance (chain D and resid   16 and name OH ), (chain G and resid    1 and name N  )
distance (chain D and resid   17 and name O  ), (chain T and resid   18 and name N  )
distance (chain D and resid   18 and name O  ), (chain H and resid   19 and name N  )
distance (chain D and resid   19 and name O  ), (chain D and resid   21 and name N  )
distance (chain D and resid   19 and name O  ), (chain T and resid   20 and name N  )
distance (chain D and resid   20 and name O  ), (chain D and resid   22 and name N  )
distance (chain D and resid   20 and name O  ), (chain D and resid   23 and name N  )
distance (chain D and resid   21 and name OE1), (chain F and resid    1 and name N  )
distance (chain D and resid   21 and name OE1), (chain J and resid    1 and name N  )
distance (chain D and resid   21 and name O  ), (chain H and resid   22 and name N  )
distance (chain D and resid   21 and name OE2), (chain D and resid   22 and name NH1)
distance (chain D and resid   21 and name OE2), (chain J and resid    1 and name N  )
distance (chain D and resid   22 and name O  ), (chain H and resid   23 and name N  )
distance (chain D and resid   23 and name O  ), (chain D and resid   25 and name N  )
distance (chain D and resid   23 and name O  ), (chain H and resid   24 and name N  )
distance (chain D and resid   25 and name O  ), (chain T and resid   26 and name N  )
distance (chain D and resid   27 and name O  ), (chain D and resid   29 and name NZ )
distance (chain C and resid    1 and name O  ), (chain D and resid   16 and name OH )
distance (chain C and resid    1 and name O  ), (chain G and resid    1 and name N  )
distance (chain C and resid    1 and name O  ), (chain G and resid    2 and name N  )
distance (chain C and resid    2 and name O  ), (chain S and resid    3 and name N  )
distance (chain C and resid    3 and name O  ), (chain G and resid    4 and name N  )
distance (chain C and resid    4 and name OE1), (chain C and resid    5 and name NE2)
distance (chain C and resid    4 and name O  ), (chain C and resid    6 and name N  )
distance (chain C and resid    4 and name O  ), (chain S and resid    5 and name N  )
distance (chain C and resid    5 and name O  ), (chain C and resid    7 and name N  )
distance (chain C and resid    5 and name OE1), (chain S and resid    5 and name NE2)
distance (chain C and resid    6 and name O  ), (chain C and resid    9 and name OG )
distance (chain C and resid    7 and name O  ), (chain C and resid    9 and name N  )
distance (chain C and resid    7 and name O  ), (chain C and resid    9 and name OG )
distance (chain C and resid    7 and name O  ), (chain S and resid    8 and name N  )
distance (chain C and resid    9 and name O  ), (chain C and resid   11 and name N  )
distance (chain C and resid    9 and name O  ), (chain G and resid    9 and name OG )
distance (chain C and resid    9 and name OG ), (chain S and resid    9 and name N  )
distance (chain C and resid   10 and name O  ), (chain S and resid   11 and name N  )
distance (chain C and resid   11 and name O  ), (chain G and resid   12 and name N  )
distance (chain C and resid   12 and name O  ), (chain S and resid   13 and name N  )
distance (chain C and resid   13 and name O  ), (chain G and resid   14 and name N  )
distance (chain C and resid   14 and name O  ), (chain S and resid   15 and name N  )
distance (chain C and resid   15 and name OE1), (chain G and resid    1 and name N  )
distance (chain C and resid   15 and name O  ), (chain C and resid   17 and name N  )
distance (chain C and resid   15 and name O  ), (chain G and resid   16 and name N  )
distance (chain C and resid   17 and name OE1), (chain D and resid   27 and name OG1)
distance (chain C and resid   17 and name OE2), (chain D and resid   29 and name NZ )
distance (chain C and resid   18 and name OD1), (chain C and resid   15 and name NE2)
distance (chain C and resid   18 and name OD1), (chain C and resid   19 and name N  )
distance (chain C and resid   18 and name OD1), (chain S and resid   18 and name ND2)
distance (chain C and resid   19 and name O  ), (chain C and resid   21 and name N  )
distance (chain C and resid   19 and name O  ), (chain S and resid   20 and name N  )
distance (chain C and resid   21 and name OXT), (chain C and resid   18 and name ND2)
distance (chain C and resid   21 and name OXT), (chain G and resid   15 and name NE2)
distance (chain C and resid   21 and name OXT), (chain K and resid    1 and name N  )
distance (chain C and resid   21 and name OXT), (chain H and resid   16 and name OH )
distance (chain C and resid   21 and name OXT), (chain G and resid    1 and name N  )
distance (chain C and resid   21 and name OXT), (chain K and resid    1 and name N  )
distance (chain A and resid    1 and name O  ), (chain B and resid   16 and name OH )
distance (chain A and resid    1 and name O  ), (chain E and resid    1 and name N  )
distance (chain A and resid    1 and name O  ), (chain E and resid    2 and name N  )
distance (chain A and resid    2 and name O  ), (chain Q and resid    3 and name N  )
distance (chain A and resid    3 and name O  ), (chain E and resid    4 and name N  )
distance (chain A and resid    4 and name OE1), (chain A and resid    5 and name NE2)
distance (chain A and resid    4 and name O  ), (chain Q and resid    5 and name N  )
distance (chain A and resid    5 and name OE1), (chain Q and resid    5 and name NE2)
distance (chain A and resid    5 and name O  ), (chain A and resid    7 and name N  )
distance (chain A and resid    6 and name O  ), (chain A and resid    9 and name OG )
distance (chain A and resid    6 and name O  ), (chain E and resid    9 and name OG )
distance (chain A and resid    7 and name O  ), (chain A and resid    9 and name OG )
distance (chain A and resid    7 and name O  ), (chain Q and resid    8 and name N  )
distance (chain A and resid    9 and name OG ), (chain Q and resid    9 and name N  )
distance (chain A and resid    9 and name O  ), (chain A and resid   11 and name N  )
distance (chain A and resid    9 and name O  ), (chain E and resid    9 and name OG )
distance (chain A and resid   10 and name O  ), (chain Q and resid   11 and name N  )
distance (chain A and resid   11 and name O  ), (chain E and resid   12 and name N  )
distance (chain A and resid   12 and name O  ), (chain Q and resid   13 and name N  )
distance (chain A and resid   13 and name O  ), (chain E and resid   14 and name N  )
distance (chain A and resid   14 and name O  ), (chain Q and resid   15 and name N  )
distance (chain A and resid   15 and name O  ), (chain A and resid   17 and name N  )
distance (chain A and resid   15 and name O  ), (chain E and resid   16 and name N  )
distance (chain A and resid   15 and name OE1), (chain E and resid    1 and name N  )
distance (chain A and resid   17 and name OE1), (chain B and resid   27 and name OG1)
distance (chain A and resid   17 and name OE2), (chain B and resid   29 and name NZ )
distance (chain A and resid   18 and name OD1), (chain A and resid   15 and name NE2)
distance (chain A and resid   18 and name OD1), (chain Q and resid   18 and name ND2)
distance (chain A and resid   19 and name O  ), (chain A and resid   21 and name N  )
distance (chain A and resid   19 and name O  ), (chain Q and resid   20 and name N  )
distance (chain A and resid   21 and name O  ), (chain F and resid   16 and name OH )
distance (chain A and resid   21 and name O  ), (chain E and resid    1 and name N  )
distance (chain A and resid   21 and name O  ), (chain I and resid    1 and name N  )
distance (chain A and resid   21 and name OXT), (chain A and resid   18 and name ND2)
distance (chain A and resid   21 and name OXT), (chain E and resid   15 and name NE2)
distance (chain A and resid   21 and name OXT), (chain I and resid    1 and name N  )
distance (chain F and resid    1 and name O  ), (chain J and resid    2 and name N  )
distance (chain F and resid    2 and name O  ), (chain B and resid    3 and name N  )
distance (chain F and resid    3 and name OD1), (chain B and resid    3 and name ND2)
distance (chain F and resid    3 and name O  ), (chain J and resid    4 and name N  )
distance (chain F and resid    4 and name O  ), (chain F and resid    6 and name N  )
distance (chain F and resid    5 and name O  ), (chain B and resid    6 and name N  )
distance (chain F and resid    6 and name O  ), (chain J and resid    7 and name N  )
distance (chain F and resid    7 and name O  ), (chain J and resid    8 and name N  )
distance (chain F and resid    8 and name O  ), (chain B and resid    9 and name N  )
distance (chain F and resid    9 and name O  ), (chain J and resid    9 and name OG )
distance (chain F and resid    9 and name O  ), (chain J and resid   10 and name N  )
distance (chain F and resid   10 and name O  ), (chain B and resid   11 and name N  )
distance (chain F and resid   11 and name O  ), (chain B and resid   12 and name N  )
distance (chain F and resid   12 and name O  ), (chain J and resid   13 and name N  )
distance (chain F and resid   13 and name O  ), (chain B and resid   14 and name N  )
distance (chain F and resid   13 and name OE1), (chain J and resid   10 and name ND1)
distance (chain F and resid   14 and name O  ), (chain J and resid   15 and name N  )
distance (chain F and resid   15 and name O  ), (chain B and resid   16 and name N  )
distance (chain F and resid   16 and name OH ), (chain I and resid    1 and name N  )
distance (chain F and resid   16 and name O  ), (chain F and resid   18 and name N  )
distance (chain F and resid   17 and name O  ), (chain B and resid   18 and name N  )
distance (chain F and resid   18 and name O  ), (chain J and resid   19 and name N  )
distance (chain F and resid   19 and name O  ), (chain B and resid   20 and name N  )
distance (chain F and resid   20 and name O  ), (chain F and resid   22 and name N  )
distance (chain F and resid   20 and name O  ), (chain F and resid   23 and name N  )
distance (chain F and resid   21 and name OE2), (chain F and resid   22 and name NH1)
distance (chain F and resid   21 and name OE2), (chain L and resid    1 and name N  )
distance (chain F and resid   21 and name O  ), (chain J and resid   22 and name N  )
distance (chain F and resid   21 and name OE1), (chain H and resid    1 and name N  )
distance (chain F and resid   21 and name OE1), (chain L and resid    1 and name N  )
distance (chain F and resid   22 and name O  ), (chain J and resid   23 and name N  )
distance (chain F and resid   23 and name O  ), (chain F and resid   25 and name N  )
distance (chain F and resid   23 and name O  ), (chain J and resid   24 and name N  )
distance (chain F and resid   25 and name O  ), (chain B and resid   26 and name N  )
distance (chain F and resid   27 and name O  ), (chain F and resid   29 and name NZ )
distance (chain H and resid    1 and name O  ), (chain L and resid    2 and name N  )
distance (chain H and resid    2 and name O  ), (chain D and resid    3 and name N  )
distance (chain H and resid    3 and name OD1), (chain D and resid    3 and name ND2)
distance (chain H and resid    3 and name O  ), (chain L and resid    4 and name N  )
distance (chain H and resid    5 and name O  ), (chain D and resid    6 and name N  )
distance (chain H and resid    6 and name O  ), (chain L and resid    7 and name N  )
distance (chain H and resid    7 and name O  ), (chain L and resid    8 and name N  )
distance (chain H and resid    8 and name O  ), (chain D and resid    9 and name N  )
distance (chain H and resid    9 and name OG ), (chain H and resid   10 and name N  )
distance (chain H and resid    9 and name O  ), (chain L and resid    9 and name OG )
distance (chain H and resid    9 and name O  ), (chain L and resid   10 and name N  )
distance (chain H and resid   10 and name O  ), (chain D and resid   11 and name N  )
distance (chain H and resid   11 and name O  ), (chain D and resid   12 and name N  )
distance (chain H and resid   12 and name O  ), (chain L and resid   13 and name N  )
distance (chain H and resid   13 and name O  ), (chain D and resid   14 and name N  )
distance (chain H and resid   13 and name OE1), (chain L and resid   10 and name ND1)
distance (chain H and resid   14 and name O  ), (chain L and resid   15 and name N  )
distance (chain H and resid   15 and name O  ), (chain D and resid   16 and name N  )
distance (chain H and resid   16 and name O  ), (chain H and resid   18 and name N  )
distance (chain H and resid   16 and name OH ), (chain K and resid    1 and name N  )
distance (chain H and resid   17 and name O  ), (chain D and resid   18 and name N  )
distance (chain H and resid   18 and name O  ), (chain L and resid   19 and name N  )
distance (chain H and resid   19 and name O  ), (chain D and resid   20 and name N  )
distance (chain H and resid   19 and name O  ), (chain H and resid   21 and name N  )
distance (chain H and resid   20 and name O  ), (chain H and resid   22 and name N  )
distance (chain H and resid   20 and name O  ), (chain H and resid   23 and name N  )
distance (chain H and resid   21 and name OE1), (chain J and resid    1 and name N  )
distance (chain H and resid   21 and name O  ), (chain L and resid   22 and name N  )
distance (chain H and resid   21 and name OE2), (chain H and resid   22 and name NH1)
distance (chain H and resid   22 and name O  ), (chain L and resid   23 and name N  )
distance (chain H and resid   23 and name O  ), (chain H and resid   25 and name N  )
distance (chain H and resid   23 and name O  ), (chain L and resid   24 and name N  )
distance (chain H and resid   25 and name O  ), (chain D and resid   26 and name N  )
distance (chain H and resid   27 and name O  ), (chain H and resid   29 and name NZ )
distance (chain G and resid    1 and name O  ), (chain H and resid   16 and name OH )
distance (chain G and resid    1 and name O  ), (chain K and resid    1 and name N  )
distance (chain G and resid    1 and name O  ), (chain K and resid    2 and name N  )
distance (chain G and resid    2 and name O  ), (chain C and resid    3 and name N  )
distance (chain G and resid    3 and name O  ), (chain K and resid    4 and name N  )
distance (chain G and resid    4 and name OE1), (chain G and resid    5 and name NE2)
distance (chain G and resid    4 and name O  ), (chain C and resid    5 and name N  )
distance (chain G and resid    4 and name O  ), (chain G and resid    6 and name N  )
distance (chain G and resid    5 and name O  ), (chain G and resid    7 and name N  )
distance (chain G and resid    5 and name OE1), (chain C and resid    5 and name NE2)
distance (chain G and resid    6 and name O  ), (chain G and resid    9 and name OG )
distance (chain G and resid    7 and name O  ), (chain C and resid    8 and name N  )
distance (chain G and resid    7 and name O  ), (chain G and resid    9 and name N  )
distance (chain G and resid    7 and name O  ), (chain G and resid    9 and name OG )
distance (chain G and resid    9 and name O  ), (chain G and resid   11 and name N  )
distance (chain G and resid    9 and name O  ), (chain K and resid    9 and name OG )
distance (chain G and resid    9 and name OG ), (chain C and resid    9 and name N  )
distance (chain G and resid   10 and name O  ), (chain C and resid   11 and name N  )
distance (chain G and resid   11 and name O  ), (chain K and resid   12 and name N  )
distance (chain G and resid   12 and name O  ), (chain C and resid   13 and name N  )
distance (chain G and resid   13 and name O  ), (chain K and resid   14 and name N  )
distance (chain G and resid   14 and name O  ), (chain C and resid   15 and name N  )
distance (chain G and resid   15 and name OE1), (chain K and resid    1 and name N  )
distance (chain G and resid   15 and name O  ), (chain G and resid   17 and name N  )
distance (chain G and resid   15 and name O  ), (chain K and resid   16 and name N  )
distance (chain G and resid   17 and name OE1), (chain H and resid   27 and name OG1)
distance (chain G and resid   17 and name OE2), (chain H and resid   29 and name NZ )
distance (chain G and resid   18 and name OD1), (chain C and resid   18 and name ND2)
distance (chain G and resid   18 and name OD1), (chain G and resid   15 and name NE2)
distance (chain G and resid   18 and name OD1), (chain G and resid   19 and name N  )
distance (chain G and resid   19 and name O  ), (chain C and resid   20 and name N  )
distance (chain G and resid   19 and name O  ), (chain G and resid   21 and name N  )
distance (chain G and resid   21 and name OXT), (chain G and resid   18 and name ND2)
distance (chain G and resid   21 and name OXT), (chain K and resid   15 and name NE2)
distance (chain G and resid   21 and name OXT), (chain L and resid   16 and name OH )
distance (chain G and resid   21 and name OXT), (chain K and resid    1 and name N  )
distance (chain E and resid    1 and name O  ), (chain F and resid   16 and name OH )
distance (chain E and resid    1 and name O  ), (chain I and resid    1 and name N  )
distance (chain E and resid    1 and name O  ), (chain I and resid    2 and name N  )
distance (chain E and resid    2 and name O  ), (chain A and resid    3 and name N  )
distance (chain E and resid    3 and name O  ), (chain I and resid    4 and name N  )
distance (chain E and resid    4 and name OE1), (chain E and resid    5 and name NE2)
distance (chain E and resid    4 and name O  ), (chain A and resid    5 and name N  )
distance (chain E and resid    5 and name OE1), (chain A and resid    5 and name NE2)
distance (chain E and resid    5 and name O  ), (chain E and resid    7 and name N  )
distance (chain E and resid    6 and name O  ), (chain E and resid    9 and name OG )
distance (chain E and resid    6 and name O  ), (chain I and resid    9 and name OG )
distance (chain E and resid    7 and name O  ), (chain A and resid    8 and name N  )
distance (chain E and resid    7 and name O  ), (chain E and resid    9 and name OG )
distance (chain E and resid    9 and name OG ), (chain A and resid    9 and name N  )
distance (chain E and resid    9 and name O  ), (chain E and resid   11 and name N  )
distance (chain E and resid    9 and name O  ), (chain I and resid    9 and name OG )
distance (chain E and resid   10 and name O  ), (chain A and resid   11 and name N  )
distance (chain E and resid   11 and name O  ), (chain I and resid   12 and name N  )
distance (chain E and resid   12 and name O  ), (chain A and resid   13 and name N  )
distance (chain E and resid   13 and name O  ), (chain I and resid   14 and name N  )
distance (chain E and resid   14 and name O  ), (chain A and resid   15 and name N  )
distance (chain E and resid   15 and name O  ), (chain E and resid   17 and name N  )
distance (chain E and resid   15 and name O  ), (chain I and resid   16 and name N  )
distance (chain E and resid   15 and name OE1), (chain I and resid    1 and name N  )
distance (chain E and resid   17 and name OE1), (chain F and resid   27 and name OG1)
distance (chain E and resid   17 and name OE2), (chain F and resid   29 and name NZ )
distance (chain E and resid   18 and name OD1), (chain A and resid   18 and name ND2)
distance (chain E and resid   18 and name OD1), (chain E and resid   15 and name NE2)
distance (chain E and resid   19 and name O  ), (chain A and resid   20 and name N  )
distance (chain E and resid   19 and name O  ), (chain E and resid   21 and name N  )
distance (chain E and resid   21 and name O  ), (chain J and resid   16 and name OH )
distance (chain E and resid   21 and name O  ), (chain I and resid    1 and name N  )
distance (chain E and resid   21 and name OXT), (chain E and resid   18 and name ND2)
distance (chain E and resid   21 and name OXT), (chain I and resid   15 and name NE2)
distance (chain J and resid    2 and name O  ), (chain F and resid    3 and name N  )
distance (chain J and resid    3 and name OD1), (chain F and resid    3 and name ND2)
distance (chain J and resid    4 and name O  ), (chain J and resid    6 and name N  )
distance (chain J and resid    5 and name O  ), (chain F and resid    6 and name N  )
distance (chain J and resid    8 and name O  ), (chain F and resid    9 and name N  )
distance (chain J and resid   10 and name O  ), (chain F and resid   11 and name N  )
distance (chain J and resid   11 and name O  ), (chain F and resid   12 and name N  )
distance (chain J and resid   13 and name O  ), (chain F and resid   14 and name N  )
distance (chain J and resid   15 and name O  ), (chain F and resid   16 and name N  )
distance (chain J and resid   16 and name O  ), (chain J and resid   18 and name N  )
distance (chain J and resid   17 and name O  ), (chain F and resid   18 and name N  )
distance (chain J and resid   19 and name O  ), (chain F and resid   20 and name N  )
distance (chain J and resid   20 and name O  ), (chain J and resid   22 and name N  )
distance (chain J and resid   20 and name O  ), (chain J and resid   23 and name N  )
distance (chain J and resid   21 and name OE2), (chain J and resid   22 and name NH1)
distance (chain J and resid   21 and name OE1), (chain L and resid    1 and name N  )
distance (chain J and resid   23 and name O  ), (chain J and resid   25 and name N  )
distance (chain J and resid   25 and name O  ), (chain F and resid   26 and name N  )
distance (chain J and resid   27 and name O  ), (chain J and resid   29 and name NZ )
distance (chain L and resid    2 and name O  ), (chain H and resid    3 and name N  )
distance (chain L and resid    3 and name OD1), (chain H and resid    3 and name ND2)
distance (chain L and resid    5 and name O  ), (chain H and resid    6 and name N  )
distance (chain L and resid    8 and name O  ), (chain H and resid    9 and name N  )
distance (chain L and resid    9 and name OG ), (chain L and resid   10 and name N  )
distance (chain L and resid   10 and name O  ), (chain H and resid   11 and name N  )
distance (chain L and resid   11 and name O  ), (chain H and resid   12 and name N  )
distance (chain L and resid   13 and name O  ), (chain H and resid   14 and name N  )
distance (chain L and resid   15 and name O  ), (chain H and resid   16 and name N  )
distance (chain L and resid   16 and name O  ), (chain L and resid   18 and name N  )
distance (chain L and resid   17 and name O  ), (chain H and resid   18 and name N  )
distance (chain L and resid   19 and name O  ), (chain H and resid   20 and name N  )
distance (chain L and resid   19 and name O  ), (chain L and resid   21 and name N  )
distance (chain L and resid   20 and name O  ), (chain L and resid   22 and name N  )
distance (chain L and resid   20 and name O  ), (chain L and resid   23 and name N  )
distance (chain L and resid   21 and name OE2), (chain L and resid   22 and name NH1)
distance (chain L and resid   23 and name O  ), (chain L and resid   25 and name N  )
distance (chain L and resid   25 and name O  ), (chain H and resid   26 and name N  )
distance (chain L and resid   27 and name O  ), (chain L and resid   29 and name NZ )
distance (chain K and resid    1 and name O  ), (chain L and resid   16 and name OH )
distance (chain K and resid    2 and name O  ), (chain G and resid    3 and name N  )
distance (chain K and resid    4 and name OE1), (chain K and resid    5 and name NE2)
distance (chain K and resid    4 and name O  ), (chain G and resid    5 and name N  )
distance (chain K and resid    4 and name O  ), (chain K and resid    6 and name N  )
distance (chain K and resid    5 and name O  ), (chain K and resid    7 and name N  )
distance (chain K and resid    5 and name OE1), (chain G and resid    5 and name NE2)
distance (chain K and resid    6 and name O  ), (chain K and resid    9 and name OG )
distance (chain K and resid    7 and name O  ), (chain G and resid    8 and name N  )
distance (chain K and resid    7 and name O  ), (chain K and resid    9 and name N  )
distance (chain K and resid    7 and name O  ), (chain K and resid    9 and name OG )
distance (chain K and resid    9 and name O  ), (chain K and resid   11 and name N  )
distance (chain K and resid    9 and name OG ), (chain G and resid    9 and name N  )
distance (chain K and resid   10 and name O  ), (chain G and resid   11 and name N  )
distance (chain K and resid   12 and name O  ), (chain G and resid   13 and name N  )
distance (chain K and resid   14 and name O  ), (chain G and resid   15 and name N  )
distance (chain K and resid   15 and name O  ), (chain K and resid   17 and name N  )
distance (chain K and resid   17 and name OE1), (chain L and resid   27 and name OG1)
distance (chain K and resid   17 and name OE2), (chain L and resid   29 and name NZ )
distance (chain K and resid   18 and name OD1), (chain G and resid   18 and name ND2)
distance (chain K and resid   18 and name OD1), (chain K and resid   15 and name NE2)
distance (chain K and resid   18 and name OD1), (chain K and resid   19 and name N  )
distance (chain K and resid   19 and name O  ), (chain G and resid   20 and name N  )
distance (chain K and resid   19 and name O  ), (chain K and resid   21 and name N  )
distance (chain K and resid   21 and name OXT), (chain K and resid   18 and name ND2)
distance (chain I and resid    1 and name O  ), (chain J and resid   16 and name OH )
distance (chain I and resid    2 and name O  ), (chain E and resid    3 and name N  )
distance (chain I and resid    4 and name OE1), (chain I and resid    5 and name NE2)
distance (chain I and resid    4 and name O  ), (chain E and resid    5 and name N  )
distance (chain I and resid    5 and name OE1), (chain E and resid    5 and name NE2)
distance (chain I and resid    5 and name O  ), (chain I and resid    7 and name N  )
distance (chain I and resid    6 and name O  ), (chain I and resid    9 and name OG )
distance (chain I and resid    7 and name O  ), (chain E and resid    8 and name N  )
distance (chain I and resid    7 and name O  ), (chain I and resid    9 and name OG )
distance (chain I and resid    9 and name OG ), (chain E and resid    9 and name N  )
distance (chain I and resid    9 and name O  ), (chain I and resid   11 and name N  )
distance (chain I and resid   10 and name O  ), (chain E and resid   11 and name N  )
distance (chain I and resid   12 and name O  ), (chain E and resid   13 and name N  )
distance (chain I and resid   14 and name O  ), (chain E and resid   15 and name N  )
distance (chain I and resid   15 and name O  ), (chain I and resid   17 and name N  )
distance (chain I and resid   17 and name OE1), (chain J and resid   27 and name OG1)
distance (chain I and resid   17 and name OE2), (chain J and resid   29 and name NZ )
distance (chain I and resid   18 and name OD1), (chain E and resid   18 and name ND2)
distance (chain I and resid   18 and name OD1), (chain I and resid   15 and name NE2)
distance (chain I and resid   19 and name O  ), (chain E and resid   20 and name N  )
distance (chain I and resid   19 and name O  ), (chain I and resid   21 and name N  )
distance (chain I and resid   21 and name OXT), (chain I and resid   18 and name ND2)
distance (chain N and resid    1 and name O  ), (chain R and resid    2 and name N  )
distance (chain N and resid    3 and name O  ), (chain R and resid    4 and name N  )
distance (chain N and resid    4 and name O  ), (chain N and resid    6 and name N  )
distance (chain N and resid    6 and name O  ), (chain R and resid    7 and name N  )
distance (chain N and resid    7 and name O  ), (chain R and resid    8 and name N  )
distance (chain N and resid    9 and name O  ), (chain R and resid    9 and name OG )
distance (chain N and resid    9 and name O  ), (chain R and resid   10 and name N  )
distance (chain N and resid   12 and name O  ), (chain R and resid   13 and name N  )
distance (chain N and resid   13 and name OE1), (chain R and resid   10 and name ND1)
distance (chain N and resid   14 and name O  ), (chain R and resid   15 and name N  )
distance (chain N and resid   16 and name OH ), (chain Q and resid    1 and name N  )
distance (chain N and resid   16 and name O  ), (chain N and resid   18 and name N  )
distance (chain N and resid   18 and name O  ), (chain R and resid   19 and name N  )
distance (chain N and resid   20 and name O  ), (chain N and resid   22 and name N  )
distance (chain N and resid   20 and name O  ), (chain N and resid   23 and name N  )
distance (chain N and resid   21 and name OE2), (chain N and resid   22 and name NH1)
distance (chain N and resid   21 and name OE2), (chain T and resid    1 and name N  )
distance (chain N and resid   21 and name O  ), (chain R and resid   22 and name N  )
distance (chain N and resid   21 and name OE1), (chain P and resid    1 and name N  )
distance (chain N and resid   21 and name OE1), (chain T and resid    1 and name N  )
distance (chain N and resid   22 and name O  ), (chain R and resid   23 and name N  )
distance (chain N and resid   23 and name O  ), (chain N and resid   25 and name N  )
distance (chain N and resid   23 and name O  ), (chain R and resid   24 and name N  )
distance (chain N and resid   27 and name O  ), (chain N and resid   29 and name NZ )
distance (chain P and resid    1 and name O  ), (chain T and resid    2 and name N  )
distance (chain P and resid    3 and name O  ), (chain T and resid    4 and name N  )
distance (chain P and resid    6 and name O  ), (chain T and resid    7 and name N  )
distance (chain P and resid    7 and name O  ), (chain T and resid    8 and name N  )
distance (chain P and resid    9 and name OG ), (chain P and resid   10 and name N  )
distance (chain P and resid    9 and name O  ), (chain T and resid    9 and name OG )
distance (chain P and resid    9 and name O  ), (chain T and resid   10 and name N  )
distance (chain P and resid   12 and name O  ), (chain T and resid   13 and name N  )
distance (chain P and resid   13 and name OE1), (chain T and resid   10 and name ND1)
distance (chain P and resid   14 and name O  ), (chain T and resid   15 and name N  )
distance (chain P and resid   16 and name O  ), (chain P and resid   18 and name N  )
distance (chain P and resid   16 and name OH ), (chain S and resid    1 and name N  )
distance (chain P and resid   18 and name O  ), (chain T and resid   19 and name N  )
distance (chain P and resid   19 and name O  ), (chain P and resid   21 and name N  )
distance (chain P and resid   20 and name O  ), (chain P and resid   22 and name N  )
distance (chain P and resid   20 and name O  ), (chain P and resid   23 and name N  )
distance (chain P and resid   21 and name OE1), (chain B and resid    1 and name N  )
distance (chain P and resid   21 and name OE1), (chain R and resid    1 and name N  )
distance (chain P and resid   21 and name O  ), (chain T and resid   22 and name N  )
distance (chain P and resid   21 and name OE2), (chain B and resid    1 and name N  )
distance (chain P and resid   21 and name OE2), (chain P and resid   22 and name NH1)
distance (chain P and resid   22 and name O  ), (chain T and resid   23 and name N  )
distance (chain P and resid   23 and name O  ), (chain P and resid   25 and name N  )
distance (chain P and resid   23 and name O  ), (chain T and resid   24 and name N  )
distance (chain P and resid   27 and name O  ), (chain P and resid   29 and name NZ )
distance (chain O and resid    1 and name O  ), (chain P and resid   16 and name OH )
distance (chain O and resid    1 and name O  ), (chain S and resid    1 and name N  )
distance (chain O and resid    1 and name O  ), (chain S and resid    2 and name N  )
distance (chain O and resid    3 and name O  ), (chain S and resid    4 and name N  )
distance (chain O and resid    4 and name OE1), (chain O and resid    5 and name NE2)
distance (chain O and resid    4 and name O  ), (chain O and resid    6 and name N  )
distance (chain O and resid    5 and name O  ), (chain O and resid    7 and name N  )
distance (chain O and resid    6 and name O  ), (chain O and resid    9 and name OG )
distance (chain O and resid    7 and name O  ), (chain O and resid    9 and name N  )
distance (chain O and resid    7 and name O  ), (chain O and resid    9 and name OG )
distance (chain O and resid    9 and name O  ), (chain O and resid   11 and name N  )
distance (chain O and resid    9 and name O  ), (chain S and resid    9 and name OG )
distance (chain O and resid   11 and name O  ), (chain S and resid   12 and name N  )
distance (chain O and resid   13 and name O  ), (chain S and resid   14 and name N  )
distance (chain O and resid   15 and name OE1), (chain S and resid    1 and name N  )
distance (chain O and resid   15 and name O  ), (chain O and resid   17 and name N  )
distance (chain O and resid   15 and name O  ), (chain S and resid   16 and name N  )
distance (chain O and resid   17 and name OE1), (chain P and resid   27 and name OG1)
distance (chain O and resid   17 and name OE2), (chain P and resid   29 and name NZ )
distance (chain O and resid   18 and name OD1), (chain O and resid   15 and name NE2)
distance (chain O and resid   18 and name OD1), (chain O and resid   19 and name N  )
distance (chain O and resid   19 and name O  ), (chain O and resid   21 and name N  )
distance (chain O and resid   21 and name OXT), (chain C and resid    1 and name N  )
distance (chain O and resid   21 and name OXT), (chain O and resid   18 and name ND2)
distance (chain O and resid   21 and name OXT), (chain S and resid   15 and name NE2)
distance (chain O and resid   21 and name OXT), (chain C and resid    1 and name N  )
distance (chain O and resid   21 and name OXT), (chain T and resid   16 and name OH )
distance (chain O and resid   21 and name OXT), (chain S and resid    1 and name N  )
distance (chain M and resid    1 and name O  ), (chain N and resid   16 and name OH )
distance (chain M and resid    1 and name O  ), (chain Q and resid    1 and name N  )
distance (chain M and resid    1 and name O  ), (chain Q and resid    2 and name N  )
distance (chain M and resid    3 and name O  ), (chain Q and resid    4 and name N  )
distance (chain M and resid    4 and name OE1), (chain M and resid    5 and name NE2)
distance (chain M and resid    5 and name O  ), (chain M and resid    7 and name N  )
distance (chain M and resid    6 and name O  ), (chain M and resid    9 and name OG )
distance (chain M and resid    6 and name O  ), (chain Q and resid    9 and name OG )
distance (chain M and resid    7 and name O  ), (chain M and resid    9 and name OG )
distance (chain M and resid    9 and name O  ), (chain M and resid   11 and name N  )
distance (chain M and resid    9 and name O  ), (chain Q and resid    9 and name OG )
distance (chain M and resid   11 and name O  ), (chain Q and resid   12 and name N  )
distance (chain M and resid   13 and name O  ), (chain Q and resid   14 and name N  )
distance (chain M and resid   15 and name O  ), (chain M and resid   17 and name N  )
distance (chain M and resid   15 and name O  ), (chain Q and resid   16 and name N  )
distance (chain M and resid   15 and name OE1), (chain Q and resid    1 and name N  )
distance (chain M and resid   17 and name OE1), (chain N and resid   27 and name OG1)
distance (chain M and resid   17 and name OE2), (chain N and resid   29 and name NZ )
distance (chain M and resid   18 and name OD1), (chain M and resid   15 and name NE2)
distance (chain M and resid   19 and name O  ), (chain M and resid   21 and name N  )
distance (chain M and resid   21 and name O  ), (chain A and resid    1 and name N  )
distance (chain M and resid   21 and name O  ), (chain R and resid   16 and name OH )
distance (chain M and resid   21 and name O  ), (chain Q and resid    1 and name N  )
distance (chain M and resid   21 and name OXT), (chain A and resid    1 and name N  )
distance (chain M and resid   21 and name OXT), (chain M and resid   18 and name ND2)
distance (chain M and resid   21 and name OXT), (chain Q and resid   15 and name NE2)
distance (chain R and resid    1 and name O  ), (chain B and resid    2 and name N  )
distance (chain R and resid    2 and name O  ), (chain N and resid    3 and name N  )
distance (chain R and resid    3 and name OD1), (chain N and resid    3 and name ND2)
distance (chain R and resid    3 and name O  ), (chain B and resid    4 and name N  )
distance (chain R and resid    4 and name O  ), (chain R and resid    6 and name N  )
distance (chain R and resid    5 and name O  ), (chain N and resid    6 and name N  )
distance (chain R and resid    6 and name O  ), (chain B and resid    7 and name N  )
distance (chain R and resid    7 and name O  ), (chain B and resid    8 and name N  )
distance (chain R and resid    8 and name O  ), (chain N and resid    9 and name N  )
distance (chain R and resid    9 and name O  ), (chain B and resid    9 and name OG )
distance (chain R and resid    9 and name O  ), (chain B and resid   10 and name N  )
distance (chain R and resid   10 and name O  ), (chain N and resid   11 and name N  )
distance (chain R and resid   11 and name O  ), (chain N and resid   12 and name N  )
distance (chain R and resid   12 and name O  ), (chain B and resid   13 and name N  )
distance (chain R and resid   13 and name O  ), (chain N and resid   14 and name N  )
distance (chain R and resid   13 and name OE1), (chain B and resid   10 and name ND1)
distance (chain R and resid   14 and name O  ), (chain B and resid   15 and name N  )
distance (chain R and resid   15 and name O  ), (chain N and resid   16 and name N  )
distance (chain R and resid   16 and name OH ), (chain A and resid    1 and name N  )
distance (chain R and resid   16 and name O  ), (chain R and resid   18 and name N  )
distance (chain R and resid   17 and name O  ), (chain N and resid   18 and name N  )
distance (chain R and resid   18 and name O  ), (chain B and resid   19 and name N  )
distance (chain R and resid   19 and name O  ), (chain N and resid   20 and name N  )
distance (chain R and resid   20 and name O  ), (chain R and resid   22 and name N  )
distance (chain R and resid   20 and name O  ), (chain R and resid   23 and name N  )
distance (chain R and resid   21 and name OE2), (chain D and resid    1 and name N  )
distance (chain R and resid   21 and name OE2), (chain R and resid   22 and name NH1)
distance (chain R and resid   21 and name O  ), (chain B and resid   22 and name N  )
distance (chain R and resid   21 and name OE1), (chain D and resid    1 and name N  )
distance (chain R and resid   21 and name OE1), (chain T and resid    1 and name N  )
distance (chain R and resid   22 and name O  ), (chain B and resid   23 and name N  )
distance (chain R and resid   23 and name O  ), (chain B and resid   24 and name N  )
distance (chain R and resid   23 and name O  ), (chain R and resid   25 and name N  )
distance (chain R and resid   25 and name O  ), (chain N and resid   26 and name N  )
distance (chain R and resid   27 and name O  ), (chain R and resid   29 and name NZ )
distance (chain T and resid    1 and name O  ), (chain D and resid    2 and name N  )
distance (chain T and resid    2 and name O  ), (chain P and resid    3 and name N  )
distance (chain T and resid    3 and name OD1), (chain P and resid    3 and name ND2)
distance (chain T and resid    3 and name O  ), (chain D and resid    4 and name N  )
distance (chain T and resid    5 and name O  ), (chain P and resid    6 and name N  )
distance (chain T and resid    6 and name O  ), (chain D and resid    7 and name N  )
distance (chain T and resid    7 and name O  ), (chain D and resid    8 and name N  )
distance (chain T and resid    8 and name O  ), (chain P and resid    9 and name N  )
distance (chain T and resid    9 and name OG ), (chain T and resid   10 and name N  )
distance (chain T and resid    9 and name O  ), (chain D and resid    9 and name OG )
distance (chain T and resid    9 and name O  ), (chain D and resid   10 and name N  )
distance (chain T and resid   10 and name O  ), (chain P and resid   11 and name N  )
distance (chain T and resid   11 and name O  ), (chain P and resid   12 and name N  )
distance (chain T and resid   12 and name O  ), (chain D and resid   13 and name N  )
distance (chain T and resid   13 and name O  ), (chain P and resid   14 and name N  )
distance (chain T and resid   13 and name OE1), (chain D and resid   10 and name ND1)
distance (chain T and resid   14 and name O  ), (chain D and resid   15 and name N  )
distance (chain T and resid   15 and name O  ), (chain P and resid   16 and name N  )
distance (chain T and resid   16 and name O  ), (chain T and resid   18 and name N  )
distance (chain T and resid   16 and name OH ), (chain C and resid    1 and name N  )
distance (chain T and resid   17 and name O  ), (chain P and resid   18 and name N  )
distance (chain T and resid   18 and name O  ), (chain D and resid   19 and name N  )
distance (chain T and resid   19 and name O  ), (chain P and resid   20 and name N  )
distance (chain T and resid   19 and name O  ), (chain T and resid   21 and name N  )
distance (chain T and resid   20 and name O  ), (chain T and resid   22 and name N  )
distance (chain T and resid   20 and name O  ), (chain T and resid   23 and name N  )
distance (chain T and resid   21 and name OE1), (chain B and resid    1 and name N  )
distance (chain T and resid   21 and name OE1), (chain F and resid    1 and name N  )
distance (chain T and resid   21 and name O  ), (chain D and resid   22 and name N  )
distance (chain T and resid   21 and name OE2), (chain F and resid    1 and name N  )
distance (chain T and resid   21 and name OE2), (chain T and resid   22 and name NH1)
distance (chain T and resid   22 and name O  ), (chain D and resid   23 and name N  )
distance (chain T and resid   23 and name O  ), (chain D and resid   24 and name N  )
distance (chain T and resid   23 and name O  ), (chain T and resid   25 and name N  )
distance (chain T and resid   25 and name O  ), (chain P and resid   26 and name N  )
distance (chain T and resid   27 and name O  ), (chain T and resid   29 and name NZ )
distance (chain S and resid    1 and name O  ), (chain C and resid    1 and name N  )
distance (chain S and resid    1 and name O  ), (chain C and resid    2 and name N  )
distance (chain S and resid    1 and name O  ), (chain T and resid   16 and name OH )
distance (chain S and resid    2 and name O  ), (chain O and resid    3 and name N  )
distance (chain S and resid    3 and name O  ), (chain C and resid    4 and name N  )
distance (chain S and resid    4 and name OE1), (chain S and resid    5 and name NE2)
distance (chain S and resid    4 and name O  ), (chain O and resid    5 and name N  )
distance (chain S and resid    4 and name O  ), (chain S and resid    6 and name N  )
distance (chain S and resid    5 and name O  ), (chain S and resid    7 and name N  )
distance (chain S and resid    5 and name OE1), (chain O and resid    5 and name NE2)
distance (chain S and resid    6 and name O  ), (chain S and resid    9 and name OG )
distance (chain S and resid    7 and name O  ), (chain O and resid    8 and name N  )
distance (chain S and resid    7 and name O  ), (chain S and resid    9 and name N  )
distance (chain S and resid    7 and name O  ), (chain S and resid    9 and name OG )
distance (chain S and resid    9 and name O  ), (chain C and resid    9 and name OG )
distance (chain S and resid    9 and name O  ), (chain S and resid   11 and name N  )
distance (chain S and resid    9 and name OG ), (chain O and resid    9 and name N  )
distance (chain S and resid   10 and name O  ), (chain O and resid   11 and name N  )
distance (chain S and resid   11 and name O  ), (chain C and resid   12 and name N  )
distance (chain S and resid   12 and name O  ), (chain O and resid   13 and name N  )
distance (chain S and resid   13 and name O  ), (chain C and resid   14 and name N  )
distance (chain S and resid   14 and name O  ), (chain O and resid   15 and name N  )
distance (chain S and resid   15 and name OE1), (chain C and resid    1 and name N  )
distance (chain S and resid   15 and name O  ), (chain C and resid   16 and name N  )
distance (chain S and resid   15 and name O  ), (chain S and resid   17 and name N  )
distance (chain S and resid   17 and name OE1), (chain T and resid   27 and name OG1)
distance (chain S and resid   17 and name OE2), (chain T and resid   29 and name NZ )
distance (chain S and resid   18 and name OD1), (chain O and resid   18 and name ND2)
distance (chain S and resid   18 and name OD1), (chain S and resid   15 and name NE2)
distance (chain S and resid   18 and name OD1), (chain S and resid   19 and name N  )
distance (chain S and resid   19 and name O  ), (chain O and resid   20 and name N  )
distance (chain S and resid   19 and name O  ), (chain S and resid   21 and name N  )
distance (chain S and resid   21 and name OXT), (chain C and resid   15 and name NE2)
distance (chain S and resid   21 and name OXT), (chain G and resid    1 and name N  )
distance (chain S and resid   21 and name OXT), (chain S and resid   18 and name ND2)
distance (chain S and resid   21 and name OXT), (chain D and resid   16 and name OH )
distance (chain S and resid   21 and name OXT), (chain C and resid    1 and name N  )
distance (chain S and resid   21 and name OXT), (chain G and resid    1 and name N  )
distance (chain Q and resid    1 and name O  ), (chain A and resid    1 and name N  )
distance (chain Q and resid    1 and name O  ), (chain A and resid    2 and name N  )
distance (chain Q and resid    1 and name O  ), (chain R and resid   16 and name OH )
distance (chain Q and resid    2 and name O  ), (chain M and resid    3 and name N  )
distance (chain Q and resid    3 and name O  ), (chain A and resid    4 and name N  )
distance (chain Q and resid    4 and name OE1), (chain Q and resid    5 and name NE2)
distance (chain Q and resid    4 and name O  ), (chain M and resid    5 and name N  )
distance (chain Q and resid    5 and name OE1), (chain M and resid    5 and name NE2)
distance (chain Q and resid    5 and name O  ), (chain Q and resid    7 and name N  )
distance (chain Q and resid    6 and name O  ), (chain A and resid    9 and name OG )
distance (chain Q and resid    6 and name O  ), (chain Q and resid    9 and name OG )
distance (chain Q and resid    7 and name O  ), (chain M and resid    8 and name N  )
distance (chain Q and resid    7 and name O  ), (chain Q and resid    9 and name OG )
distance (chain Q and resid    9 and name OG ), (chain M and resid    9 and name N  )
distance (chain Q and resid    9 and name O  ), (chain A and resid    9 and name OG )
distance (chain Q and resid    9 and name O  ), (chain Q and resid   11 and name N  )
distance (chain Q and resid   10 and name O  ), (chain M and resid   11 and name N  )
distance (chain Q and resid   11 and name O  ), (chain A and resid   12 and name N  )
distance (chain Q and resid   12 and name O  ), (chain M and resid   13 and name N  )
distance (chain Q and resid   13 and name O  ), (chain A and resid   14 and name N  )
distance (chain Q and resid   14 and name O  ), (chain M and resid   15 and name N  )
distance (chain Q and resid   15 and name O  ), (chain A and resid   16 and name N  )
distance (chain Q and resid   15 and name O  ), (chain Q and resid   17 and name N  )
distance (chain Q and resid   15 and name OE1), (chain A and resid    1 and name N  )
distance (chain Q and resid   17 and name OE1), (chain R and resid   27 and name OG1)
distance (chain Q and resid   17 and name OE2), (chain R and resid   29 and name NZ )
distance (chain Q and resid   18 and name OD1), (chain M and resid   18 and name ND2)
distance (chain Q and resid   18 and name OD1), (chain Q and resid   15 and name NE2)
distance (chain Q and resid   19 and name O  ), (chain M and resid   20 and name N  )
distance (chain Q and resid   19 and name O  ), (chain Q and resid   21 and name N  )
distance (chain Q and resid   21 and name O  ), (chain B and resid   16 and name OH )
distance (chain Q and resid   21 and name O  ), (chain A and resid    1 and name N  )
distance (chain Q and resid   21 and name O  ), (chain E and resid    1 and name N  )
distance (chain Q and resid   21 and name OXT), (chain A and resid   15 and name NE2)
distance (chain Q and resid   21 and name OXT), (chain E and resid    1 and name N  )
distance (chain Q and resid   21 and name OXT), (chain Q and resid   18 and name ND2)
